flyway.url=jdbc:postgresql://localhost:5450/xayara_indonesia
flyway.user=postgres
flyway.password=admin
flyway.locations=filesystem:database/migrations
flyway.baselineOnMigrate=true
flyway.table=flyway_schema_history
