;/*FB_PKG_DELIM*/

__d("BaseAspectRatioContainer.react",["FBLogger","react","react-strict-dom"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){var t=e.aspectRatio,n=e.children,a=e.contentStyle,i=e.testid,l=e.xstyle;if(t<=0)throw r("FBLogger")("comet_ui").mustfixThrow("Aspect ratio must be a non-zero, positive number: %s",t);return s.jsx(o("react-strict-dom").html.div,{"data-testid":void 0,style:[d.container,l,d.dynamicTop(t)],children:n!=null&&s.jsx(o("react-strict-dom").html.div,{style:[d.content,a],children:n})})}u.displayName=u.name+" [from "+i.id+"]";var c={paddingTop:"x1jm3axb",$$css:!0},d={container:{height:"xqtp20y",position:"x1n2onr6",width:"xh8yej3",$$css:!0},content:{alignItems:"x1qjc9v5",borderBottomStyle:"x1q0q8m5",borderBottomWidth:"x1qhh985",borderInlineEndStyle:"x18b5jzi",borderInlineEndWidth:"x10w94by",borderInlineStartStyle:"x1t7ytsu",borderInlineStartWidth:"x14e42zd",borderTopStyle:"x13fuv20",borderTopWidth:"x972fbf",bottom:"x1ey2m1c",boxSizing:"x9f619",display:"x78zum5",flexDirection:"xdt5ytf",flexGrow:"x1iyjqo2",flexShrink:"xs83m0k",insetInlineEnd:"xtijo5x",insetInlineStart:"x1o0tod",left:null,right:null,justifyContent:"x1qughib",marginBottom:"xat24cr",marginInlineEnd:"x14z9mp",marginInlineStart:"x1lziwak",marginTop:"xdj266r",minHeight:"x2lwn1j",minWidth:"xeuugli",paddingBottom:"x18d9i69",paddingInlineEnd:"xyri2b",paddingInlineStart:"x1c1uobl",paddingTop:"xexx8yu",position:"x10l6tqk",top:"x13vifvy",zIndex:"x1ja2u2z",$$css:!0},dynamicTop:function(t){return[c,{"--x-paddingTop":(function(e){return typeof e=="number"?e+"px":e!=null?e:void 0})(100/t+"%")}]}};l.default=u}),98);
__d("BaseSvgImage.react",["react"],(function(t,n,r,o,a,i,l){"use strict";var e=["onError","src","testid"],s,u=s||(s=o("react")),c=s,d=c.useEffect,m=c.useRef;function p(t){var n=t.onError,r=t.src,o=t.testid,a=babelHelpers.objectWithoutPropertiesLoose(t,e),i=m(null),l=m(r);return d(function(){if(i.current&&i.current.getAttribute("xlink:href")!==l.current){var e;(e=i.current)==null||e.setAttribute("xlink:href",l.current)}},[]),u.jsx("image",babelHelpers.extends({},a,{"data-testid":void 0,height:"100%",onError:n,preserveAspectRatio:"xMidYMid slice",ref:i,width:"100%",xlinkHref:r}))}p.displayName=p.name+" [from "+i.id+"]",l.default=p}),98);
__d("CAAApiApp",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum")({FACEBOOK:"facebook",INSTAGRAM:"instagram",MESSENGER:"messenger",PRIME:"prime",THREADS:"threads",WHATSAPP:"whatsapp"}),l=e;i.default=l}),66);
__d("CAAFetaIGLoginHomepageQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27358518663786364"}),null);
__d("CAAFetaIGLoginHomepageQuery$Parameters",["CAAFetaIGLoginHomepageQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CAAFetaIGLoginHomepageQuery_facebookRelayOperation"),metadata:{},name:"CAAFetaIGLoginHomepageQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("MAEntAccountTypeErrorUtils",["FBLogger"],(function(t,n,r,o,a,i,l){"use strict";function e(e){throw r("FBLogger")("fx_core_infra").mustfixThrow("Unexpected MAEntAccountType default case hit: %s",e)}function s(e){return r("FBLogger")("fx_core_infra").mustfix("Unexpected MAEntAccountType default case hit: %s",e),null}l.throwUnexpectedMAEntAccountTypeError=e,l.logUnexpectedMAEntAccountTypeError=s}),98);
__d("XMDSDivider.react",["BaseDivider.react","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){var t=e.xstyle;return s.jsx(r("BaseDivider.react"),{xstyle:t})}u.displayName=u.name+" [from "+i.id+"]",l.default=u}),98);
__d("XMDSTheme.react",["cr:2671","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));l.default=n("cr:2671")}),98);
__d("XMDSThemeV1.react",["BaseTheme.react","CometTransientDialogProvider.react","XMDSThemeConfig","react"],(function(t,n,r,o,a,i,l){"use strict";var e=["children"],s,u=s||(s=o("react"));function c(t){var n=t.children,o=babelHelpers.objectWithoutPropertiesLoose(t,e);return u.jsx(r("BaseTheme.react"),babelHelpers.extends({config:r("XMDSThemeConfig")},o,{children:u.jsx(r("CometTransientDialogProvider.react"),{children:n})}))}c.displayName=c.name+" [from "+i.id+"]",l.default=c}),98);